---
title: "Signif_custome_category_heatmap"
author: "Kazu"
date: "10/24/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

# custom category heatmap (Fig. 5)
# Making list of custom catetory genes enriched in shade responsive genes (TableS7 for Fig5)
```{r}
## start from this line ## 052616
# fold chagne (shade responsiveness)
load(file.path("..","..","Nozue2016_SAStranscriptome_output","output","summary.vst.response.Rdata") )
dim(summary.vst.response) #[1] 30533    52
head(summary.vst.response)
# find overlap between shade responsive (in Col) and hormone responsive
#test<-read.csv(file.path("..","..","Nozue2016_SAStranscriptome_output","figs_tables","TableS4_hormone.responsiveness.SOMclusters100717.csv") ,row.names=1) # needs to use updated one (092917)
test<-read.csv(file.path("..","..","Nozue2016_SAStranscriptome_output","figs_tables","Dataset2_Custom_enrichment_tsnedbscan_clusters_of_shade-responsive_genes101917v3.csv") ,row.names=1) # tsnedbscan version
test<-test %>% select(-c(Short_description,colE...col.F))
colnames(test)
test<-test %>% filter(gt==1) %>% select(-gt) # select only found in Col clusters. remove gt column

# reading overlapTable
#load(file.path("..","..","Nozue2016_SAStranscriptome_output","output","overlap.GOseq.melt.summary.SOM.customcat.100717.Rdata")) 
overlap.melt.tsnedbscan.customcat.PLoSGenetics2015mutants.errrDE.summary.files<-list.files(file.path("..","..","Nozue2016_SAStranscriptome_output","output","tsne_dbscan_overlapTable_heatmap"),pattern="overlap.melt.tsnedbscan.customcat.PLoSGenetics2015mutants.errrDE.summary")

for(y in overlap.melt.tsnedbscan.customcat.PLoSGenetics2015mutants.errrDE.summary.files) 
  { # 140 of y
  load(file.path("..","..","Nozue2016_SAStranscriptome_output","output","tsne_dbscan_overlapTable_heatmap",y))
overlap.melt.summary.s<-overlap.melt.summary[!overlap.melt.summary$Var1==0,] # remove cluster "0"
overlap.melt.summary.s<-overlap.melt.summary.s[!overlap.melt.summary.s$Var2=="",]
overlap.melt.summary.s$Var2<-droplevels(overlap.melt.summary.s$Var2)
# select log10>2 & !Var1==0 
overlap.melt.summary.s.significant<-overlap.melt.summary.s[overlap.melt.summary.s$value> -log10(0.01),] # pvalue<0.01 (the same as Fig3)
overlap.melt.summary.s.significant$category.cluster<-with(overlap.melt.summary.s.significant,paste(Var2,Var1,sep="_")) # Var1 = cluster, Var2=category

title<-gsub("(overlap.melt.tsnedbscan.customcat.PLoSGenetics2015mutants.errrDE.summary)(\\.)(eps[[:print:]]+)(\\_)(MinPts[[:digit:]]+)(\\.)(set)(\\.)([[:digit:]]+)(\\.Rdata)","\\3\\4\\5\\6\\7\\9",y)


test.wozero<-test[!test[,title]=="0",c(grep("eps",colnames(test),invert=TRUE,value=TRUE),title)] # remove cluster 0 in test
head(test.wozero)
test.wozero.melt<-melt(test.wozero,id.var=c("AGI",title))
colnames(test.wozero.melt)<-gsub(title,"cluster",colnames(test.wozero.melt))
head(test.wozero.melt)
dim(test.wozero.melt) #6061 4
test.wozero.melt<-test.wozero.melt %>% select(-variable) %>% filter(!value=="")
dim(test.wozero.melt) #191 4
table(test.wozero.melt$AGI) # all Col with "title" 

# # remove small group (less than 3)
#category.morethan3<-names(table(overlap.melt.summary.s.significant$value)[table(test.wozero.melt.hormone.significant$value)>3])
#category.morethan3<-overlap.melt.summary.s.significant %>% count(Var2) %>% filter(n>3) %>% as.data.frame()

test.wozero.melt$category.cluster<-with(test.wozero.melt,paste(value,cluster,sep="_"))
# select (1) category morethan 3 within test.wozero.melt 
#         (2) 
# %>% filter(value %in% category.morethan3$Var2)
test.wozero.melt.hormone.significant<- test.wozero.melt %>% filter(category.cluster %in% overlap.melt.summary.s.significant$category.cluster)
test.wozero.melt.hormone.significant
category.significnat.morethan3<-test.wozero.melt.hormone.significant %>% count(value) %>% filter(n>3) %>% as.data.frame()

if(dim(category.significnat.morethan3)[1]==0) {next} else {

overlap.melt.summary.s.significant$value<-as.character(overlap.melt.summary.s.significant$value)
# test.wozero.melt.hormone.significant.s is my category marker gene list 
test.wozero.melt.hormone.significant.s<-test.wozero.melt.hormone.significant[,c("AGI","value")]
names(test.wozero.melt.hormone.significant.s)<-c("AGI","my.category")
test.wozero.melt.hormone.significant.s.summary<-table(test.wozero.melt.hormone.significant.s)[,-1]
table(test.wozero.melt.hormone.significant.s$my.category)
##

# temp.list<-list()
# for(i in levels(as.factor(test.wozero.melt.hormone.significant.s$AGI))) {
#   temp.list[[i]]<-test.wozero.melt.hormone.significant.s[grep(i,test.wozero.melt.hormone.significant.s$AGI),"my.category"]
# }
######
test.wozero.melt.hormone.significant.s
# reformatting 
test2<-data.frame(AGI=unique(test.wozero.melt.hormone.significant.s$AGI))
my.category<-levels(as.factor(test.wozero.melt.hormone.significant.s$my.category))
for(n in 1:length(my.category)) {
  temp<-rep("",dim(test2)[1])
  names(temp)<-test2$AGI
test.wozero.melt.hormone.significant.s[test.wozero.melt.hormone.significant.s$my.category==my.category[n],"AGI"]
temp[test2$AGI %in% test.wozero.melt.hormone.significant.s[test.wozero.melt.hormone.significant.s$my.category==my.category[n],"AGI"]]<-my.category[n]
temp
test2<-cbind(test2, temp)
}
colnames(test2)[-1]<-my.category
# alternative way
test3<-tidyr::unite(test2, my.category2, colnames(test2)[-1], sep="",remove=TRUE)
category.morethan3.v2<-test3 %>% count(my.category2) %>% filter(n>3) %>% as.data.frame()
test.wozero.melt.hormone.significant.s　%>% count(my.category)
save(test.wozero.melt.hormone.significant.s,file=file.path("..","..","Nozue2016_SAStranscriptome_output","output","tsne_dbscan_overlapTable_heatmap",paste("test.wozero.melt.hormone.significant.s.",title,".Rdata",sep="")))
} # category.morethan3 > 0
} # 
```
# comparison of test.wozero.melt.hormone.significant.s gene list (102517)
```{r}
test.wozero.melt.hormone.significant.s.files<-list.files(pattern="test.wozero.melt.hormone.significant.s",path=file.path("..","..","Nozue2016_SAStranscriptome_output","output","tsne_dbscan_overlapTable_heatmap"))

 test.wozero.melt.hormone.significant.s.list<- sapply(file.path("..","..","Nozue2016_SAStranscriptome_output","output","tsne_dbscan_overlapTable_heatmap",test.wozero.melt.hormone.significant.s.files),function(x) mget(load(x))) # mget 
# rename 
names(test.wozero.melt.hormone.significant.s.list)<-gsub("(../../Nozue2016_SAStranscriptome_output/output/tsne_dbscan_overlapTable_heatmap/test.wozero.melt.hormone.significant.s.)(eps[[:print:]]+)(\\_)(MinPts[[:digit:]]+)(\\.)(set[[:digit:]]+)(.Rdata.test.wozero.melt.hormone.significant.s)","\\2\\3\\4\\5\\6",names(test.wozero.melt.hormone.significant.s.list))
 
test.wozero.melt.hormone.significant.s.list2<-sapply(test.wozero.melt.hormone.significant.s.list,c)
test.wozero.melt.hormone.significant.s.list2["AGI",] # compare this with heatmap (Fig3) for double chekcing
test.wozero.melt.hormone.significant.s.list2["AGI",] %>% sapply(length)

```
# 



# how to look overlap between categories?
```{r}
dim(test.wozero.melt.hormone.significant.s.summary) # 93 10
# pTable
for(i in 2:8) {
  for(n in (i+1):9) {
category.overlapTable<-overlapTable(test.wozero.melt.hormone.significant.s.summary[,i],test.wozero.melt.hormone.significant.s.summary[,n])
category.overlapTable.pTable<-category.overlapTable$pTable
    save(category.overlapTable.pTable,file=file.path("..","..","Nozue2016_SAStranscriptome_output","output","tsne_dbscan_overlapTable_heatmap",paste("category.overlapTable.pTable",colnames(test.wozero.melt.hormone.significant.s.summary)[i],colnames(test.wozero.melt.hormone.significant.s.summary)[n],"Rdata",sep=".")))
  }
}
# combine pTable
category.overlapTable.pTable.files<-list.files(pattern="category.overlapTable.pTable",path=file.path("..","..","Nozue2016_SAStranscriptome_output","output","tsne_dbscan_overlapTable_heatmap"))

category.overlapTable.pTable.files.list<-sapply(file.path("..","..","Nozue2016_SAStranscriptome_output","output","tsne_dbscan_overlapTable_heatmap",category.overlapTable.pTable.files),function(x) mget(load(x))) # mget 
names(category.overlapTable.pTable.files.list)<-gsub("(../../Nozue2016_SAStranscriptome_output/output/tsne_dbscan_overlapTable_heatmap/category.overlapTable.pTable.)([[:print:]]+)(.Rdata.category.overlap)","\\2",names(category.overlapTable.pTable.files.list))
#category.overlapTable.files.DF<-as.data.frame(category.overlapTable.files.list)
p.table<-data.frame(comparison=rep("",length(names(category.overlapTable.files.list))),signif.overlap="")
p.table[1,2]<-category.overlapTable.files.list[[1]][2,2]
p.table[1,1]<-gsub("([[:print:]]+)(Table.pTable)","\\1",names(category.overlapTable.files.list)[1])

for(n in 2:length(names(category.overlapTable.files.list))) {
p.table[n,2]<-category.overlapTable.files.list[[n]][2,2]
p.table[n,1]<-gsub("([[:print:]]+)(Table.pTable)","\\1",names(category.overlapTable.files.list)[n])
}
p.table
# count
for(i in 1:9) {
  for(n in (i+1):10) {
category.overlapTable<-overlapTable(test.wozero.melt.hormone.significant.s.summary[,i],test.wozero.melt.hormone.significant.s.summary[,n])
category.overlapTable.countTable<-category.overlapTable$countTable
    save(category.overlapTable.countTable,file=file.path("..","..","Nozue2016_SAStranscriptome_output","output","tsne_dbscan_overlapTable_heatmap",paste("category.overlapTable.count",colnames(test.wozero.melt.hormone.significant.s.summary)[i],colnames(test.wozero.melt.hormone.significant.s.summary)[n],"Rdata",sep=".")))
  }
}
# count
category.overlapTable.count.files<-list.files(pattern="category.overlapTable.count",path=file.path("..","..","Nozue2016_SAStranscriptome_output","output","tsne_dbscan_overlapTable_heatmap"))

category.overlapTable.count.files.list<-sapply(file.path("..","..","Nozue2016_SAStranscriptome_output","output","tsne_dbscan_overlapTable_heatmap",category.overlapTable.count.files),function(x) mget(load(x))) # mget 
names(category.overlapTable.count.files.list)<-gsub("(../../Nozue2016_SAStranscriptome_output/output/tsne_dbscan_overlapTable_heatmap/category.overlapTable.count.)([[:print:]]+)(.Rdata.category.overlap)","\\2",names(category.overlapTable.count.files.list))
#category.overlapTable.files.DF<-as.data.frame(category.overlapTable.files.list)
count.table<-data.frame(comparison=rep("",length(names(category.overlapTable.count.files.list))),count.overlap="")
count.table[1,2]<-category.overlapTable.count.files.list[[1]][2,2]
count.table[1,1]<-gsub("([[:print:]]+)(Table.countTable)","\\1",names(category.overlapTable.count.files.list)[1])

for(n in 2:length(names(category.overlapTable.count.files.list))) {
count.table[n,2]<-category.overlapTable.count.files.list[[n]][2,2]
count.table[n,1]<-gsub("([[:print:]]+)(Table.countTable)","\\1",names(category.overlapTable.count.files.list)[n])
}
count.table

#### combine signif.overlap and count.overlap
p.table.count<-merge(p.table,count.table,by="comparison")
p.table.count$x<-gsub("([[:print:]]+)(\\.)([[:print:]]+)","\\1",p.table.count$comparison)
p.table.count$y<-gsub("([[:print:]]+)(\\.)([[:print:]]+)","\\3",p.table.count$comparison)
# contingent table format
p.table.count.reshape<-reshape(data=p.table.count[,c("x","y","count.overlap")],idvar="x",timevar="y",direction="wide")
colnames(p.table.count.reshape)<-gsub("count.overlap.","",colnames(p.table.count.reshape))
p.table.count.reshape
p.table.count.reshape[is.na(p.table.count.reshape)]<-""
p.table.count.reshape

######## under construction ######### 102417
# 


##############
test.wozero.melt.hormone.significant.ss<-test.wozero.melt.hormone.significant.s[!test.wozero.melt.hormone.significant.s$my.category %in% c("BLup","MJdown","MYC234up","NPR1up","NPR1down","NPR1down_uponSA","NPR1up_uponSA","WRKY33up","WRKY33down","SAup_24h"),] # eliminate those categories

# remove my.category =="" (092917)
test.wozero.melt.hormone.significant.ss<-test.wozero.melt.hormone.significant.ss[!test.wozero.melt.hormone.significant.ss$my.category=="",]
table(test.wozero.melt.hormone.significant.ss$my.category)
 # ABAdown    ABAup    ACCup   BLdown     CKup  IAAdown    IAAup     MJup SARminus  SARplus 
 #       9        4        5        4        2        2       44       20        1        6 

#write.csv(test.wozero.melt.hormone.significant.ss,file=file.path("..","..","Nozue2016_SAStranscriptome_output","figs_tables","TableS6_test.wozero.melt.hormone.significant.ss.100717.csv")) # 
#### what genes do belong to multiple categories?
#reshape(test.wozero.melt.hormone.significant.s,idvar="AGI",timevar="my.category",direction="wide")
test.wozero.melt.hormone.significant.s.summary<-table(test.wozero.melt.hormone.significant.s)[,-1]
# specific to each category (fixed 101017)
test.wozero.melt.hormone.significant.s.summary.specific<-test.wozero.melt.hormone.significant.s.summary[rowSums(test.wozero.melt.hormone.significant.s.summary)==1,] # need to merge SA related categories?
test.wozero.melt.hormone.significant.s.summary.specific 
duplicated(rownames(test.wozero.melt.hormone.significant.s.summary.specific))
## 
reshape(test.wozero.melt.hormone.significant.ss,idvar="AGI",timevar="my.category",direction="wide") #  should be test.wozero.melt.hormone.significant.s.summary.specific
test.wozero.melt.hormone.significant.ss.summary<-table(test.wozero.melt.hormone.significant.s)[,-1]
test.wozero.melt.hormone.significant.ss.summary # table object

test.wozero.melt.hormone.significant.sss<-test.wozero.melt.hormone.significant.ss[test.wozero.melt.hormone.significant.ss$AGI %in% test.wozero.melt.hormone.significant.ss$AGI,] # 
test.wozero.melt.hormone.significant.sss<-test.wozero.melt.hormone.significant.ss[test.wozero.melt.hormone.significant.ss$AGI %in% rownames(test.wozero.melt.hormone.significant.s.summary.specific),] # revised. 101017
dim(test.wozero.melt.hormone.significant.sss) # 48 2
table(test.wozero.melt.hormone.significant.sss$my.category)
# ABAdown   ABAup   ACCup  BLdown    CKup IAAdown   IAAup    MJup SARplus 
#       3       1       2       2       1       1      25       9       2 
# needs to eliminate categories less than 3 genes
category.morethan3<-names(table(test.wozero.melt.hormone.significant.sss$my.category))[table(test.wozero.melt.hormone.significant.sss$my.category)>2]
test.wozero.melt.hormone.significant.ssss<-test.wozero.melt.hormone.significant.sss[test.wozero.melt.hormone.significant.sss$my.category %in% category.morethan3,]
dim(test.wozero.melt.hormone.significant.ssss) #37 2
table(test.wozero.melt.hormone.significant.sss$my.category)
table(test.wozero.melt.hormone.significant.ssss$my.category)
# ABAdown   IAAup    MJup 
#       3      25      9 

}


write.csv(test.wozero.melt.hormone.significant.ssss,file="../../Nozue2016_SAStranscriptome_output/figs_tables/TableS6_test.wozero.melt.hormone.significant.102417.csv") # This should be TableS6 (101017)
```
